# Generated by Django 5.2 on 2025-04-30 13:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('nume', models.CharField(max_length=20)),
                ('magazin', models.CharField(max_length=20, null=True)),
                ('pret', models.FloatField(max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.UUID('654d6007-9a11-4889-a75e-fbca399554d3'), editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
